# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: frontend-service-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | b64enc }}
