# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
