name: Build, Push Docker Image & Deploy with Helm

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
           username: sentdexcloud9
           password: dckr_pat_0kblbWQ-0yNByU-TCF6QR9dfS7g
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_PASSWORD }}
# DOCKERHUB_USERNAME=sentdexcloud9
# DOCKERHUB_PASSWORD=dckr_pat_0kblbWQ-0yNByU-TCF6QR9dfS7g
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sentdexcloud9/frontend-service:latest



      - name: Upload assets folder to S3 bucket
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

          aws s3 cp ./assets s3://testmytradeassets/assets --recursive
          aws s3 ls s3://testmytradeassets/assets

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Upgrade Helm deployment
        if: success()  # Runs only if the Kubernetes context setup succeeded
        run: |

          rm kubeconfig.yaml -f
          wget https://testmytradeassets.s3.us-east-1.amazonaws.com/kubeconfig.yaml
          export KUBECONFIG=./kubeconfig.yaml  # Reference your repo kubeconfig file
          kubectl config current-context  # Verify the context
          kubectl get pods
          helm upgrade --install frontend-service ./helm_frontend_chart --namespace=default
          kubectl rollout restart deployment frontend-service-frontend-service -n default

